app_name = "red_statutory"
app_title = "RED Statutory"
app_publisher = "REDANCHOR"
app_description = "REDANCHOR Statutory Registers & Labour Compliance"
app_email = "info@redanchor.in"
app_license = "MIT"